"""empty message

Revision ID: 793b1fed9f0b
Revises: bef850c6773e
Create Date: 2022-02-12 11:03:26.701965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '793b1fed9f0b'
down_revision = 'bef850c6773e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('planet_id', sa.Integer(), nullable=True))
    op.drop_constraint('favorites_ibfk_2', 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'planet', ['planet_id'], ['id'])
    op.drop_column('favorites', 'planets_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('planets_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key('favorites_ibfk_2', 'favorites', 'planet', ['planets_id'], ['id'])
    op.drop_column('favorites', 'planet_id')
    # ### end Alembic commands ###
